services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  mongo:
    image: mongo:4.4.28
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongopw
    volumes:
      - mongodata:/var/lib/mongodb/data
volumes:
  pgdata:
  mongodata:  
